name: Update alias.json from API structure

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

permissions:
  contents: write

env:
  API_URL: ${{ secrets.API_URL }}

jobs:
  update-alias:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Update alias.json
        run: python fetch_alias.py

      - name: Commit and push if alias.json changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add alias.json
          git diff --cached --quiet || (git commit -m "ci: Update alias.json from API structure" && git push)
